name: farming_assistant
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  weather: ^3.1.1
  geolocator: ^13.0.2
  intl: ^0.18.1
  provider: ^6.1.1
  cupertino_icons: ^1.0.8
  perfect_freehand: ^2.3.2
  flutter_colorpicker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/navigation_icons/
    - assets/weather_icons/