name: Commit Message Check
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  check-commit-message:
    name: Check Commit Message Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Check commit messages
        run: |
          # Get all commit messages in the PR
          git fetch origin ${{ github.base_ref }}
          commits=$(git log --format=%s origin/${{ github.base_ref }}..${{ github.event.pull_request.head.sha }})
          
          # Check each commit message
          echo "$commits" | while IFS= read -r msg; do
            if [ -n "$msg" ]; then # Skip empty lines
              if ! [[ "$msg" =~ ^FA-[0-9]+:\ *.+ ]]; then
                echo "❌ Error: Invalid commit message format: $msg"
                echo "✨ Required format: FA-<number>: <message>"
                echo "📝 Example: FA-123: Add login feature"
                exit 1
              fi
            fi
          done